package charles.nocompany.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import charles.nocompany.greendao.TestTable1;

import charles.nocompany.greendao.TestTable1Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testTable1DaoConfig;

    private final TestTable1Dao testTable1Dao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testTable1DaoConfig = daoConfigMap.get(TestTable1Dao.class).clone();
        testTable1DaoConfig.initIdentityScope(type);

        testTable1Dao = new TestTable1Dao(testTable1DaoConfig, this);

        registerDao(TestTable1.class, testTable1Dao);
    }
    
    public void clear() {
        testTable1DaoConfig.getIdentityScope().clear();
    }

    public TestTable1Dao getTestTable1Dao() {
        return testTable1Dao;
    }

}
