package charles.nocompany.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TEST_TABLE1".
 */
public class TestTable1 {

    private Long id;
    /** Not-null value. */
    private String text1;
    private String comment1;
    private java.util.Date date1;

    public TestTable1() {
    }

    public TestTable1(Long id) {
        this.id = id;
    }

    public TestTable1(Long id, String text1, String comment1, java.util.Date date1) {
        this.id = id;
        this.text1 = text1;
        this.comment1 = comment1;
        this.date1 = date1;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getText1() {
        return text1;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText1(String text1) {
        this.text1 = text1;
    }

    public String getComment1() {
        return comment1;
    }

    public void setComment1(String comment1) {
        this.comment1 = comment1;
    }

    public java.util.Date getDate1() {
        return date1;
    }

    public void setDate1(java.util.Date date1) {
        this.date1 = date1;
    }

}
